In [24]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(arr1)
print(arr1.shape)
print(np.max(arr1))
print(arr1.min())
print(arr1.mean())
std_dev = arr1.std()
print(std_dev)
newarr1 = arr1.reshape(4,5)
print(newarr1)
secound_row = newarr1[1]
print(secound_row)
third_coloum = newarr1[:,2]
print(third_coloum)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)
20
1
10.5
5.766281297335398
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 6  7  8  9 10]
[ 3  8 13 18]


In [30]:
import numpy as np
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([5,10,15,20,25])
add = arr1 + arr2
print(add)
sub = arr1 - arr2
print(sub)
mul = arr1 * arr2
print(mul)
div = arr1 / arr2
print(div)
total = arr1.sum()
print(total)

[15 30 45 60 75]
[ 5 10 15 20 25]
[  50  200  450  800 1250]
[2. 2. 2. 2. 2.]
150


In [61]:
import numpy as np
dt = np.dtype([('Roll_No','i4'),('Name','U10'),('Marks','i4')])

data = [
    (101,'Ravi',85),
    (102,'Priya',92),
    (103,'Kiran',78),
    (104,'Anu',88),
    (105,'Sita',95),
]

array = np.array(data,dtype=dt)
print(array)
print(array[:3])
avarage_marks = np.mean(array['Marks'])
print(avarage_marks)
highest_marks = np.max(array['Marks'])
print(highest_marks)
lowest_marks = np.min(array['Marks'])
print(lowest_marks)

marks = array['Marks']
conditions = [
    array['Marks']>=90,
    (array['Marks']>=80) & (array['Marks']<=89),
    array['Marks']<80
]
choices = ['A','B','C']
grades = np.select(conditions,choices)
array_grades = np.append((array,grades))
print(array_grades)

[(101, 'Ravi', 85) (102, 'Priya', 92) (103, 'Kiran', 78) (104, 'Anu', 88)
 (105, 'Sita', 95)]
[(101, 'Ravi', 85) (102, 'Priya', 92) (103, 'Kiran', 78)]
87.6
95
78


TypeError: append() missing 1 required positional argument: 'values'

In [69]:
import numpy as np

data = [
    ("Laptop",50000,10),
    ("Mouse",500,50),
    ("Keyboard",1200,30),
    ("Monitor",10000,15)
]

dtype=[('Product','U10'),('Price','i4'),('Quantity','i4')]
inventry = np.array(data,dtype=dtype)
prices = inventry['Price']
quantity = inventry['Quantity']

total = prices * quantity
print(total) 
total2= total.sum()
print(total2)
print(total.max())
print(inventry)

[500000  25000  36000 150000]
711000
500000
[('Laptop', 50000, 10) ('Mouse',   500, 50) ('Keyboard',  1200, 30)
 ('Monitor', 10000, 15)]
